### ISSUE TITLE
ERROR: open goversion.json: no such file or directory

### ISSUE THREAD

**Issue by Weimarr** [CMEPW/myph#13]
This is followed by the following Text:

```
goroutine 1 [running]:
github.com/cmepw/myph/cli.GetParser.func1(0xc0000dc300?, {0x653f71?, 0x7?, 0x65359d?})
        /root/go/pkg/mod/github.com/cmepw/myph@v1.2.1/cli/parser.go:91 +0x3c8
github.com/spf13/cobra.(*Command).execute(0xc0000e0000, {0xc0000fa050, 0x5, 0x5})
        /root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x863
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000e0300)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
main.main()
        /root/go/pkg/mod/github.com/cmepw/myph@v1.2.1/main.go:11 +0xea
```

Worked fine just a few days ago though.

**Comment by Weimarr** [comment]
I tried reinstalling, rebooting, trying on other systems but doesnt work...

**Comment by djnnvx** [comment]
Hello, 

`goversion.json` is a file that you should write yourself for the PE you wish to pack :) 
i've added an example [here](https://github.com/matro7sh/myph/blob/main/.github/test-data/example.json) 

Please be aware that:
- it will not work if there is not enough space in the binary to add/update the related section,
- you need to provide your own `.ico` / `.png` files in order to have them added as icons for the program


If the issue persists, please let me know what arguments you used, and please paste the (redacted) text files with it, if any. If I don't know what you did, I cannot replicate the bug and fix it, unfortunately :)  

Thanks
